services:
  postgres:
    image: postgres:16.3
    environment:
      POSTGRES_PASSWORD: "ratelimiterpass"
    ports:
      - "5432:5432"
  redis-server:
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"